data_dir: '../../data'

apply_enh_lee_filter: False

INPUT_HEIGHT: 200
INPUT_WIDTH: 200
INPUT_CHANNELS: 98

OUTPUT_HEIGHT: 4
OUTPUT_WIDTH: 4
OUTPUT_CHANNELS: 1

BUFFER_SIZE: 1
BATCH_SIZE: 1

EPOCHS: 10

LOAD_EXISTING: False
LOG: False

CHECKPOINT_DIR: '../../models/training_checkpoints'
LOG_DIR: '../../models/logs'

TRAIN_PATH: '../../data/tfrecords/train/train_nimgs_98.tfrecords'
VAL_PATH: '../../data/tfrecords/val/val_nimgs_49.tfrecords'

TRAIN: True
